### ISSUE TITLE
build error 'no module named thrift_compiler'

### ISSUE THREAD

**Issue by dm-jrae** [facebook/thpp#2]
Hi, I'm trying to build thpp and it errors out during the make, with 'no module named thrift_compiler'.

[  7%] Generating thpp/if/gen-cpp2/Tensor_types.h, thpp/if/gen-cpp2/Tensor_types.tcc, thpp/if/gen-cpp2/Tensor_constants.h, thpp/if/gen-cpp2/Tensor_types.cpp, thpp/if/gen-cpp2/Tensor_constants.cpp
/usr/bin/python: No module named thrift_compiler
make[2]: **\* [thpp/if/gen-cpp2/Tensor_types.h] Error 1
make[1]: **\* [CMakeFiles/thpp.dir/all] Error 2
make: **\* [all] Error 2

I am on Ubuntu 14.04, have installed folly, fbthrift, and reinstalled torch (luajit -e ';;' works).

**Comment by expersistech-gauravpathak** [comment]
Hi @dm-jrae 
How you resolved this issue? I am also facing the same issue, do I need to install any python package?

**Comment by spershin** [comment]
Just in case somebody stumbles on the problem of thrift_compiler python package not being registered/installed, here is what I did in the end to make it work.
After installing fbthrift I ended up with thrift_compiler package not being installed on the machine.
You can do it yourself if you configured, build and installed it from source.

Go to your cloned/downloaded/unpacked fbthrift, from where you ran the configure and make to build and install fbthrift. For instance for me it was:
cd /home/$USER/downloads
cd fbthrift/thrift

Then do the following (this will copy ./compiler/py folder to /usr/tmp, cd into that new py folder and run python setup script):

cp -a /compiler/py /usr/tmp
cd /usr/tmp/py
sudo python setup.py install

After that you can compile thrift files into cpp using this command (roughly):

python -mthrift_compiler.main --gen cpp2 --allow-64bit-consts -v -o "<output_dir>" -I "<some_include_path_if_you_have_includes_in_thrift_file>" "<your_beloved_thrift_file_you_need_to_compile_into_cpp"

**Comment by msiraj83** [comment]
@spershin    I am facing the same issue.... 

What i did....

- I run this `sudo python setup.py install`

- `python -mthrift_compiler.main --gen cpp2 --allow-64bit-consts -v -o  "build/"`

But the i got this error..

> python -mthrift_compiler.main --gen cpp2 --allow-64bit-consts -v -o "build/"
/usr/bin/python: cannot import name frontend

**Comment by SunnyCat2013** [comment]
`brew install boost-python`, and then recompiled `thpp` solved my problem, yet, I still don't know why...

**Comment by hzxie** [comment]
I have similar issue:
```
# python -mthrift_compiler.main --gen cpp2 --allow-64bit-consts -v -o "build/"
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.6/site-packages/thrift_py-0.9.0-py3.6.egg/thrift_compiler/__init__.py", line 1, in <module>
    import generate
  File "/opt/fblualib/build/fbthrift/thrift/compiler/py/generate/__init__.py", line 21, in <module>
    import t_generator
ModuleNotFoundError: No module named 't_generator'
```
