### ISSUE TITLE
Linker Error: undefined reference to `ZSTD_getErrorName'

### ISSUE THREAD

**Issue by mineshmathew** [facebook/thpp#21]
I was trying to install the latest release and get the following error during make. ( I could successfully install folly, wangle and thrift - the latest release which has a zstd dependancy)

`Linking CXX executable tensor_serialization_test
/users/minesh.mathew/local/lib/libthrift.so: undefined reference to`ZSTD_getErrorName'
/users/minesh.mathew/local/lib/libthrift.so: undefined reference to `ZSTD_getDecompressedSize'
/users/minesh.mathew/local/lib/libthrift.so: undefined reference to`ZSTD_compressBound'
/users/minesh.mathew/local/lib/libthrift.so: undefined reference to `ZSTD_decompress'
/users/minesh.mathew/local/lib/libthrift.so: undefined reference to`ZSTD_isError'
/users/minesh.mathew/local/lib/libthrift.so: undefined reference to `ZSTD_compress'
collect2: error: ld returned 1 exit status
make[2]: *** [test/tensor_serialization_test] Error 1
make[1]: *** [test/CMakeFiles/tensor_serialization_test.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by Soledad89** [comment]
Install zstd can solve the problem

**Comment by mineshmathew** [comment]
@Soledad89 I had zstd installed already. Thrift required it anyway.

**Comment by Arsey** [comment]
@mineshmathew I have the same issue. Were you able to fix it?

**Comment by Arsey** [comment]
@mineshmathew I've solved this problem just by commenting 

```IF(NOT NO_TESTS)
  ENABLE_TESTING()
  FIND_PACKAGE(Glog REQUIRED)
  INCLUDE_DIRECTORIES(${GLOG_INCLUDE_DIR})
  TARGET_LINK_LIBRARIES(thpp ${GLOG_LIBRARIES})
  ADD_SUBDIRECTORY("googletest-release-1.7.0")
  INCLUDE_DIRECTORIES(
    "${CMAKE_CURRENT_SOURCE_DIR}/googletest-release-1.7.0/include"
  )
  ADD_SUBDIRECTORY("test")
ENDIF()```

in `thpp/CMakeLists.txt`

it could be possible to do just with `NO_TESTS=1 ./build.sh`, but this parameter doesn't really work

**Comment by edonkeycoin** [comment]
I'm seeing the same problem trying to build the calculator sample with a fresh build and install of fbthrift (and all its dependencies) from yesterday. I've turned up build verbosity for the sample and can see that the linker is finding the installed zstd library here:

/usr/local/lib/libzstd.so

The above is a symlink that maps to the actual library:

lrwxrwxrwx 1 root root         16 Feb  2 15:12 libzstd.so -> libzstd.so.1.1.3
lrwxrwxrwx 1 root root         16 Feb  2 15:12 libzstd.so.1 -> libzstd.so.1.1.3
-rwxr-xr-x 1 root root     514013 Feb  2 15:12 libzstd.so.1.1.3

I've dumped the lib with nm to verify that the symbols that are needed by libthrift.so are present. For example:

nm /usr/local/lib/libzstd.so | grep ZSTD_getErrorName

0000000000006c20 T ZSTD_getErrorName

Yet I'm still seeing these link errors:

//usr/local/lib/libthrift.so: undefined reference to `ZSTD_getErrorName'
//usr/local/lib/libthrift.so: undefined reference to `ZSTD_getDecompressedSize'
//usr/local/lib/libthrift.so: undefined reference to `ZSTD_compressBound'
//usr/local/lib/libthrift.so: undefined reference to `ZSTD_decompress'
//usr/local/lib/libthrift.so: undefined reference to `ZSTD_isError'
//usr/local/lib/libthrift.so: undefined reference to `ZSTD_compress'

I couldn't find the CMakeLists.txt file that @Arsey mentioned. It's not clear how it would help anyway.

Any idea how to resolve this problem?

**Comment by edonkeycoin** [comment]
Never mind. I changed the order of the libs, putting -lzstd at the end, and it now links.

**Comment by tacitadeplata** [comment]
@edonkeycoin what do you meant by "putting -lzstd at the end", the end of what ? 
This issue is still not allowing me to install thpp

**Comment by edonkeycoin** [comment]
In my case simply changing the order of the libraries in the link seemed to work around the problem.

**Comment by tacitadeplata** [comment]
@edonkeycoin I guess you mean I have to turn up build verbosity to see the linker order right?

**Comment by edonkeycoin** [comment]
@tacitadeplata Probably. It would depend on your build environment. I guess I already had the verbosity turned up with sample I was playing with.

Note that in the end I found the FB fork of Thrift to be too problematic. I ended up using the Apache version instead. Performance might not be as good as the FB fork, but Apache turned out good enough for my purposes.

**Comment by tacitadeplata** [comment]
Thanks @edonkeycoin . I realized it was a problem with thrift. zstd had to be installed before installing thrift. So I removed the fbthrift directory and reinstalled it again. It detected zstd during installation properly. After that thpp builts and installs fine.
