### ISSUE TITLE
error: ‘sformat’ is not a member of ‘folly’

### ISSUE THREAD

**Issue by korkinof** [facebook/thpp#4]
Hi guys,
I'm trying to install thpp manually for fbcunn but am running into this problem.
OS is Untuntu 14.04.
Any ideas?
Best,
Dimitrios

screen dump:
../thpp/StorageSerialization-inl.h: In function ‘folly::IOBuf thpp::detail::deserialize(ThriftObj&&, thpp::ThriftTensorDataType)’:
../thpp/StorageSerialization-inl.h:62:33: error: ‘sformat’ is not a member of ‘folly’
     throw std::invalid_argument(folly::sformat(
                                 ^
../thpp/StorageSerialization-inl.h:67:33: error: ‘sformat’ is not a member of ‘folly’
     throw std::invalid_argument(folly::sformat(
                                 ^

**Comment by omry** [comment]
your folly seems out of date, can you upgrade it?

**Comment by wingsbr** [comment]
I'm running into the exact same problem (same OS, installing thpp for fbcunn, same error messages).  I cloned and built folly within the last hour, so it shouldn't be out of date.

**Comment by omry** [comment]
this is very weird, I do see sformat in folly:
https://github.com/facebook/folly/blob/master/folly/Format.h#L253

do you have it in your copy?

**Comment by wingsbr** [comment]
Yes, my copy of folly/Format.h has that, as well; very strange....

**Comment by bharris47** [comment]
I'm having the same problem. Has anyone been able to work around the issue? Installing on CentOS 7.

**Comment by ErnstHowie** [comment]
I also have the same error on Ubuntu 14.04. And I have the Format.h.

**Comment by ChangChen10** [comment]
I have the same problem.. Does anybody know how to fix it?

**Comment by soumith** [comment]
I've just built thpp on an Ubuntu 14.04 machine without any issues (with the latest folly).
What is very likely is that you have an older version of Folly on your machine as well, and that is being picked up. Find all files of folly on your machine, such as libfolly* (usually located in /usr/local/lib but maybe they've crept to other places on your machine) and /usr/local/include/folly (which is a folder with lots of headers) and delete all of those.

**Comment by ChangChen10** [comment]
Hi Soumith,
I removed all these folly*s you mentioned, and retried, but I still have this problem. (I'm using Ubuntu 14.04 on AWS g2.2xlarge machine). Are there other suggestions? Thanks a lot!!

**Comment by soumith** [comment]
@ChangChen10 I dont have any other suggestions. I just tried it myself and have no build issues, so I am not sure what else you should try.

**Comment by waterofphysics** [comment]
Facing the same problem, I've tried to remove all Folly files in /usr/local, and re-download then rebuild Folly. The identical error occurred, when I used the ./build.sh to compile thpp. Does anyone have some suggestions?

**Comment by soumith** [comment]
Can you post your folly build log (make a gist using gist.github.com . don't copy/paste in the comments here)

Also post your full thpp build log.

**Comment by waterofphysics** [comment]
@soumith Thanks a lot. I am facing this problem when I trying to install "fbcunn". My build log is posted on Gist: 
https://gist.github.com/waterofphysics/2a8ba57b489df641e8b3 . 
Hope this will be helpful.

**Comment by tudor** [comment]
Is there another copy of folly installed in /usr/include?

**Comment by soumith** [comment]
@waterofphysics you made folly but did not install it, "sudo make install"

**Comment by ErnstHowie** [comment]
I deleted all folly files in /usr/local/lib and /usr/local/include/folly. And I downloaded the latest folly-master from GitHub. Then I built and installed the folly using:
  autoreconf -ivf
  ./configure
  make
  make check
  sudo make install

I built it successfully and passed all the tests:
============================================================================
Testsuite summary for folly 34.0
============================================================================
# TOTAL: 37
# PASS:  37
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

I installed the folly without any error:
Making install in .
make[1]: Entering directory `/home/howie/ZOOSDK/Folly-master/folly'
make[2]: Entering directory `/home/howie/ZOOSDK/Folly-master/folly'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfolly.la libfollybenchmark.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libfolly.so.34.0.0 /usr/local/lib/libfolly.so.34.0.0
libtool: install: (cd /usr/local/lib && { ln -s -f libfolly.so.34.0.0 libfolly.so.34 || { rm -f libfolly.so.34 && ln -s libfolly.so.34.0.0 libfolly.so.34; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libfolly.so.34.0.0 libfolly.so || { rm -f libfolly.so && ln -s libfolly.so.34.0.0 libfolly.so; }; })
libtool: install: /usr/bin/install -c .libs/libfolly.lai /usr/local/lib/libfolly.la
libtool: install: warning: relinking `libfollybenchmark.la'
libtool: install: (cd /home/howie/ZOOSDK/Folly-master/folly; /bin/bash /home/howie/ZOOSDK/Folly-master/folly/libtool  --tag CXX --mode=relink g++ -std=gnu++0x -g -O2 -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -version-info 34:0:0 -o libfollybenchmark.la -rpath /usr/local/lib Benchmark.lo libfolly.la -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog )
libtool: relink: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o  .libs/Benchmark.o   -lboost_thread -lboost_filesystem -lboost_system -lboost_regex -lpthread -L/usr/local/lib -lfolly -llzma -lz -lsnappy -llz4 -liberty -ljemalloc -levent -ldouble-conversion -lssl -lgflags -lglog -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/4.8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o  -O2   -Wl,-soname -Wl,libfollybenchmark.so.34 -o .libs/libfollybenchmark.so.34.0.0
libtool: install: /usr/bin/install -c .libs/libfollybenchmark.so.34.0.0T /usr/local/lib/libfollybenchmark.so.34.0.0
libtool: install: (cd /usr/local/lib && { ln -s -f libfollybenchmark.so.34.0.0 libfollybenchmark.so.34 || { rm -f libfollybenchmark.so.34 && ln -s libfollybenchmark.so.34.0.0 libfollybenchmark.so.34; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libfollybenchmark.so.34.0.0 libfollybenchmark.so || { rm -f libfollybenchmark.so && ln -s libfollybenchmark.so.34.0.0 libfollybenchmark.so; }; })
libtool: install: /usr/bin/install -c .libs/libfollybenchmark.lai /usr/local/lib/libfollybenchmark.la
libtool: install: /usr/bin/install -c .libs/libfolly.a /usr/local/lib/libfolly.a
libtool: install: chmod 644 /usr/local/lib/libfolly.a
libtool: install: ranlib /usr/local/lib/libfolly.a
libtool: install: /usr/bin/install -c .libs/libfollybenchmark.a /usr/local/lib/libfollybenchmark.a
libtool: install: chmod 644 /usr/local/lib/libfollybenchmark.a
libtool: install: ranlib /usr/local/lib/libfollybenchmark.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/include/folly'
 /usr/bin/install -c -m 644  ApplyTuple.h Arena.h Arena-inl.h AtomicBitSet.h AtomicHashArray.h AtomicHashArray-inl.h AtomicHashMap.h AtomicHashMap-inl.h AtomicStruct.h Baton.h Benchmark.h Bits.h Checksum.h Chrono.h ConcurrentSkipList.h ConcurrentSkipList-inl.h Conv.h CpuId.h CPortability.h Demangle.h DiscriminatedPtr.h DynamicConverter.h dynamic.h dynamic-inl.h Exception.h ExceptionWrapper.h Executor.h EvictingCacheMap.h FBString.h FBVector.h File.h FileUtil.h Fingerprint.h folly-config.h Foreach.h FormatArg.h Format.h Format-inl.h GroupVarint.h Hash.h '/usr/local/include/folly/.'
 /usr/bin/install -c -m 644  IPAddress.h IPAddressV4.h IPAddressV6.h IPAddressException.h IndexedMemPool.h IntrusiveList.h json.h Lazy.h LifoSem.h Likely.h Logging.h MacAddress.h Malloc.h MapUtil.h Memory.h MemoryMapping.h MoveWrapper.h MPMCPipeline.h MPMCQueue.h Optional.h PackedSyncPtr.h Padded.h Portability.h Preprocessor.h ProducerConsumerQueue.h Random.h Random-inl.h Range.h RWSpinLock.h ScopeGuard.h SmallLocks.h small_vector.h SocketAddress.h sorted_vector_types.h SpinLock.h SpookyHashV1.h SpookyHashV2.h String.h String-inl.h Subprocess.h '/usr/local/include/folly/.'
 /bin/mkdir -p '/usr/local/include/folly/experimental/io'
 /usr/bin/install -c -m 644  experimental/io/FsUtil.h experimental/io/HugePages.h '/usr/local/include/folly/experimental/io'
 /bin/mkdir -p '/usr/local/include/folly/detail'
 /usr/bin/install -c -m 644  detail/AtomicHashUtils.h detail/BitIteratorDetail.h detail/BitsDetail.h detail/CacheLocality.h detail/ChecksumDetail.h detail/Clock.h detail/DiscriminatedPtrDetail.h detail/ExceptionWrapper.h detail/FileUtilDetail.h detail/FingerprintPolynomial.h detail/FunctionalExcept.h detail/Futex.h detail/GroupVarintDetail.h detail/IPAddress.h detail/Malloc.h detail/MemoryIdler.h detail/MPMCPipelineDetail.h detail/SlowFingerprint.h detail/SpinLockImpl.h detail/Stats.h detail/ThreadLocalDetail.h detail/UncaughtExceptionCounter.h '/usr/local/include/folly/detail'
 /bin/mkdir -p '/usr/local/include/folly/io/async'
 /usr/bin/install -c -m 644  io/async/AsyncTimeout.h io/async/AsyncTransport.h io/async/AsyncUDPServerSocket.h io/async/AsyncUDPSocket.h io/async/AsyncServerSocket.h io/async/AsyncSignalHandler.h io/async/AsyncSocket.h io/async/AsyncSocketBase.h io/async/AsyncSSLSocket.h io/async/AsyncSocketException.h io/async/DelayedDestruction.h io/async/EventBase.h io/async/EventBaseManager.h io/async/EventFDWrapper.h io/async/EventHandler.h io/async/EventUtil.h io/async/NotificationQueue.h io/async/HHWheelTimer.h io/async/Request.h io/async/SSLContext.h io/async/TimeoutManager.h '/usr/local/include/folly/io/async'
 /bin/mkdir -p '/usr/local/include/folly/wangle/channel'
 /usr/bin/install -c -m 644  wangle/channel/AsyncSocketHandler.h wangle/channel/ChannelHandler.h wangle/channel/ChannelHandlerContext.h wangle/channel/ChannelPipeline.h wangle/channel/OutputBufferingHandler.h '/usr/local/include/folly/wangle/channel'
 /bin/mkdir -p '/usr/local/include/folly/wangle/acceptor'
 /usr/bin/install -c -m 644  wangle/acceptor/Acceptor.h wangle/acceptor/ConnectionCounter.h wangle/acceptor/ConnectionManager.h wangle/acceptor/DomainNameMisc.h wangle/acceptor/LoadShedConfiguration.h wangle/acceptor/ManagedConnection.h wangle/acceptor/NetworkAddress.h wangle/acceptor/ServerSocketConfig.h wangle/acceptor/SocketOptions.h wangle/acceptor/TransportInfo.h '/usr/local/include/folly/wangle/acceptor'
 /bin/mkdir -p '/usr/local/include/folly/wangle/ssl'
 /usr/bin/install -c -m 644  wangle/ssl/ClientHelloExtStats.h wangle/ssl/DHParam.h wangle/ssl/PasswordInFile.h wangle/ssl/SSLCacheOptions.h wangle/ssl/SSLCacheProvider.h wangle/ssl/SSLContextConfig.h wangle/ssl/SSLContextManager.h wangle/ssl/SSLSessionCacheManager.h wangle/ssl/SSLStats.h wangle/ssl/SSLUtil.h wangle/ssl/TLSTicketKeyManager.h wangle/ssl/TLSTicketKeySeeds.h '/usr/local/include/folly/wangle/ssl'
 /bin/mkdir -p '/usr/local/include/folly/wangle/rx'
 /usr/bin/install -c -m 644  wangle/rx/Observable.h wangle/rx/Observer.h wangle/rx/Subject.h wangle/rx/Subscription.h wangle/rx/types.h '/usr/local/include/folly/wangle/rx'
 /bin/mkdir -p '/usr/local/include/folly/wangle/bootstrap'
 /usr/bin/install -c -m 644  wangle/bootstrap/ServerBootstrap.h wangle/bootstrap/ServerBootstrap-inl.h wangle/bootstrap/ServerSocketFactory.h wangle/bootstrap/ClientBootstrap.h '/usr/local/include/folly/wangle/bootstrap'
 /bin/mkdir -p '/usr/local/include/folly/test/function_benchmark'
 /usr/bin/install -c -m 644  test/function_benchmark/benchmark_impl.h test/function_benchmark/test_functions.h '/usr/local/include/folly/test/function_benchmark'
 /bin/mkdir -p '/usr/local/include/folly/futures'
 /usr/bin/install -c -m 644  futures/Deprecated.h futures/DrivableExecutor.h futures/Future-inl.h futures/Future.h futures/FutureException.h futures/InlineExecutor.h futures/ManualExecutor.h futures/OpaqueCallbackShunt.h futures/Promise-inl.h futures/Promise.h futures/QueuedImmediateExecutor.h futures/ScheduledExecutor.h futures/Timekeeper.h futures/Try-inl.h futures/Try.h '/usr/local/include/folly/futures'
 /usr/bin/install -c -m 644  Synchronized.h ThreadCachedArena.h ThreadCachedInt.h ThreadLocal.h ThreadName.h TimeoutQueue.h Traits.h Unicode.h Uri.h Uri-inl.h Varint.h VersionCheck.h '/usr/local/include/folly/.'
 /bin/mkdir -p '/usr/local/include/folly/wangle/concurrent'
 /usr/bin/install -c -m 644  wangle/concurrent/BlockingQueue.h wangle/concurrent/Codel.h wangle/concurrent/CPUThreadPoolExecutor.h wangle/concurrent/FutureExecutor.h wangle/concurrent/IOExecutor.h wangle/concurrent/IOThreadPoolExecutor.h wangle/concurrent/GlobalExecutor.h wangle/concurrent/LifoSemMPMCQueue.h wangle/concurrent/NamedThreadFactory.h wangle/concurrent/ThreadFactory.h wangle/concurrent/ThreadPoolExecutor.h '/usr/local/include/folly/wangle/concurrent'
 /bin/mkdir -p '/usr/local/include/folly/io/async/test'
 /usr/bin/install -c -m 644  io/async/test/AsyncSSLSocketTest.h io/async/test/BlockingSocket.h io/async/test/MockAsyncSocket.h io/async/test/MockAsyncServerSocket.h io/async/test/MockAsyncSSLSocket.h io/async/test/MockAsyncTransport.h io/async/test/TimeUtil.h io/async/test/UndelayedDestruction.h io/async/test/Util.h '/usr/local/include/folly/io/async/test'
 /bin/mkdir -p '/usr/local/include/folly/io'
 /usr/bin/install -c -m 644  io/Compression.h io/Cursor.h io/IOBuf.h io/IOBufQueue.h io/RecordIO.h io/RecordIO-inl.h io/TypedIOBuf.h io/ShutdownSocketSet.h '/usr/local/include/folly/io'
 /bin/mkdir -p '/usr/local/include/folly/futures/detail'
 /usr/bin/install -c -m 644  futures/detail/Core.h futures/detail/FSM.h futures/detail/ThreadWheelTimekeeper.h futures/detail/Types.h '/usr/local/include/folly/futures/detail'
 /bin/mkdir -p '/usr/local/include/folly/stats'
 /usr/bin/install -c -m 644  stats/BucketedTimeSeries-defs.h stats/BucketedTimeSeries.h stats/Histogram-defs.h stats/Histogram.h stats/MultiLevelTimeSeries-defs.h stats/MultiLevelTimeSeries.h '/usr/local/include/folly/stats'
 /bin/mkdir -p '/usr/local/include/folly/gen'
 /usr/bin/install -c -m 644  gen/Base.h gen/Base-inl.h gen/Combine.h gen/Combine-inl.h gen/Core.h gen/Core-inl.h gen/File.h gen/File-inl.h gen/Parallel.h gen/Parallel-inl.h gen/ParallelMap.h gen/ParallelMap-inl.h gen/String.h gen/String-inl.h '/usr/local/include/folly/gen'
 /bin/mkdir -p '/usr/local/include/folly/test'
 /usr/bin/install -c -m 644  test/FBStringTestBenchmarks.cpp.h test/FBVectorTestBenchmarks.cpp.h test/SynchronizedTestLib.h test/SynchronizedTestLib-inl.h '/usr/local/include/folly/test'
 /bin/mkdir -p '/usr/local/include/folly/experimental'
 /usr/bin/install -c -m 644  experimental/AutoTimer.h experimental/Bits.h experimental/EliasFanoCoding.h experimental/EventCount.h experimental/FunctionScheduler.h experimental/JSONSchema.h experimental/Select64.h experimental/SharedMutex.h experimental/Singleton.h experimental/Singleton-inl.h experimental/StringKeyedCommon.h experimental/StringKeyedUnorderedMap.h experimental/StringKeyedUnorderedSet.h experimental/TestUtil.h '/usr/local/include/folly/experimental'
make[2]: Leaving directory `/home/howie/ZOOSDK/Folly-master/folly'
make[1]: Leaving directory `/home/howie/ZOOSDK/Folly-master/folly'
Making install in test
make[1]: Entering directory `/home/howie/ZOOSDK/Folly-master/folly/test'
Making install in .
make[2]: Entering directory `/home/howie/ZOOSDK/Folly-master/folly/test'
make[3]: Entering directory `/home/howie/ZOOSDK/Folly-master/folly/test'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/home/howie/ZOOSDK/Folly-master/folly/test'
make[2]: Leaving directory `/home/howie/ZOOSDK/Folly-master/folly/test'
Making install in function_benchmark
make[2]: Entering directory `/home/howie/ZOOSDK/Folly-master/folly/test/function_benchmark'
make[3]: Entering directory `/home/howie/ZOOSDK/Folly-master/folly/test/function_benchmark'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/home/howie/ZOOSDK/Folly-master/folly/test/function_benchmark'
make[2]: Leaving directory `/home/howie/ZOOSDK/Folly-master/folly/test/function_benchmark'
make[1]: Leaving directory `/home/howie/ZOOSDK/Folly-master/folly/test'

After installation I can find the latest folly files in /usr/local/lib and /usr/local/include/folly again.
But when I tried to use the ./build.sh to build the thpp I got the same errors as before:

Scanning dependencies of target thpp
[  7%] Building CXX object CMakeFiles/thpp.dir/Storage.cpp.o
In file included from /home/howie/ZOOSDK/thpp-master/thpp/../thpp/Storage.h:172:0,
                 from /home/howie/ZOOSDK/thpp-master/thpp/Storage.cpp:11:
/home/howie/ZOOSDK/thpp-master/thpp/../thpp/StorageSerialization-inl.h: In function ‘folly::IOBuf thpp::detail::deserialize(ThriftObj&&, thpp::ThriftTensorDataType)’:
/home/howie/ZOOSDK/thpp-master/thpp/../thpp/StorageSerialization-inl.h:62:33: error: ‘sformat’ is not a member of ‘folly’
     throw std::invalid_argument(folly::sformat(
                                 ^
/home/howie/ZOOSDK/thpp-master/thpp/../thpp/StorageSerialization-inl.h:67:33: error: ‘sformat’ is not a member of ‘folly’
     throw std::invalid_argument(folly::sformat(
                                 ^
make[2]: *** [CMakeFiles/thpp.dir/Storage.cpp.o] Error 1
make[1]: *** [CMakeFiles/thpp.dir/all] Error 2
make: *** [all] Error 2

**Comment by soumith** [comment]
@ErnstHowie Give the full log of thpp build, not just the last part where it errors out. And please use gist.github.com, dont paste your log here, it's hard to read and derails the thread.

**Comment by waterofphysics** [comment]
@soumith Thanks for your reply. Sorry for my unprofessional. It may cost sometime to read the log and figure out the problem. I have updated my log file in gist: https://gist.github.com/waterofphysics/2a8ba57b489df641e8b3

I tried again and follow the steps in  https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh to compile the newly downloaded *folly* and *thpp*. Except that I download *gtest-1.7.0.zip* , which *thpp* requires, first in my laptop that can access to *googlecode.com* (which the remote server can't ),  with the *build.h* modified as 
'#rm -rf gtest-1.7.0 gtest-1.7.0.zip
rm -rf gtest-1.7.0
#curl -JLO https://googletest.googlecode.com/files/gtest-1.7.0.zip
#if [[ $(sha1sum -b gtest-1.7.0.zip | cut -d' ' -f1) != \
#      'f85f6d2481e2c6c4a18539e391aa4ea8ab0394af' ]]; then
#  echo "Invalid gtest-1.7.0.zip file" >&2
#  exit 1
#fi
unzip gtest-1.7.0.zip'

**Comment by soumith** [comment]
hello @waterofphysics , thank you for this log. It is indeed very strange that your follow installs correctly, and thpp finds the correct folly during install, yet this error appears.
Can you try one thing:
```
sudo rm -rf /usr/include/folly
sudo rm -rf /usr/local/include/folly
```

Then reinstall folly and thpp once more.
And give me the log once again.

If that does not work, can you give me the output of this command on your system (it might take some time to run):
```
find / -name "Format.h" 2>/dev/null
```

Thanks

**Comment by waterofphysics** [comment]
Hi @soumith , thank you! I ran the shell scripts that you had suggested, it failed again. However, the strange things is that there is no *folly* folder in */usr/include/*, so
''' shell
sudo rm -rf /usr/include/folly
'''
actually don't work.

And I have upload new logs in https://gist.github.com/waterofphysics/de91ee78925a2972f0b6

The final shell script works out like below.
'''
$ find / -name "Format.h" 2>/dev/null
/tmp/folly/folly/Format.h
'''

Hope these will be helpful.

**Comment by soumith** [comment]
thanks. I think I figured out the problem, pushing a patch now.

**Comment by soumith** [comment]
Okay, this should be fixed in trunk now via commit: https://github.com/facebook/thpp/commit/9e1799d8ce5356ccfc5a17da52fc36bd7d6b426d

Sorry about all this, looks like the folly team updated their repo, but we were left behind slightly. 
Let me know if anyone still has this error.

Basically, freshly clone thpp again (git clone https://github.com/facebook/thpp), and ./build.sh again

**Comment by waterofphysics** [comment]
Excellent. @soumith thank you!

**Comment by ChangChen10** [comment]
Awesome! It works now!! Many thanks!!! @soumith
