### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by rudrapoudel** [facebook/thpp#5]
Hi Guys,

I am getting following error on Ubuntu 14.04 LTS and gcc 4.8.2, I have tried some fresh build as suggested in issue #4 but no luck,

/usr/local/lib/libthriftcpp2.so: undefined reference to `folly::wangle::IOThreadPoolExecutor::IOThreadPoolExecutor(unsigned long, std::shared_ptr<folly::wangle::ThreadFactory>)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/tensor_serialization_test] Error 1
make[1]: *** [test/CMakeFiles/tensor_serialization_test.dir/all] Error 2
make: *** [all] Error 2

Many thanks,

**Comment by rudrapoudel** [comment]
Fresh build everything from the beginning solved the issue.

**Comment by TaoTaoFu** [comment]
Hi  Rudrapoudel，
I don‘t clearly know what  means the method you said :(  Rebuilding Folly  Fbthrift ?
