### ISSUE TITLE
error when running ./build.sh

### ISSUE THREAD

**Issue by freshcoderman** [facebook/thpp#50]
I am not sure if it's the problem of fbthrift, any suggestion will be appreciated
I have already change gnu++11 to gnu++14
The errors are :
[ 80%] Linking CXX executable storage_test
../libthpp.so: undefined reference to `apache::thrift::protocol::TProtocolException::throwExceededSizeLimit()'
../libthpp.so: undefined reference to `apache::thrift::protocol::TProtocolException::throwReportedTypeMismatch()'
../libthpp.so: undefined reference to `apache::thrift::util::detail::throwInvalidVarint()'
../libthpp.so: undefined reference to `apache::thrift::protocol::TProtocolException::throwMissingRequiredField(folly::Range<char const*>, folly::Range<char const*>)'
../libthpp.so: undefined reference to `apache::thrift::CompactProtocolReader::throwBadType(unsigned char)'
../libthpp.so: undefined reference to `apache::thrift::protocol::TProtocolException::throwNegativeSize()'
collect2: error: ld returned 1 exit status
test/CMakeFiles/storage_test.dir/build.make:104: recipe for target 'test/storage_test' failed
make[2]: *** [test/storage_test] Error 1
CMakeFiles/Makefile2:222: recipe for target 'test/CMakeFiles/storage_test.dir/all' failed
make[1]: *** [test/CMakeFiles/storage_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TaoTaoFu** [comment]
I meet the same error :(   @freshcoderman 
how do you solve the  problem?

**Comment by freshcoderman** [comment]
@TaoTaoFu I haven't solved that. As far as I can remember, I encountered this problem when I wanted to use CRNN. So instead, my colleague used another CRNN version based on mxnet. Anyway, I will still try to work on this problem.  If you get any solution, share that. Thank you!

**Comment by fengyang0317** [comment]
I manually move all the missing functions from this repository to apache thrift and it compiles.

**Comment by zhaoyuanxing** [comment]
@fengyang0317  i find libthriftprotocol.a in thrift‘s folder, does link this file can solve this problem? but i do not know how to link it,  can you help me?
can you share your manually changed file? thank you

**Comment by jiuhuazhao** [comment]
@freshcoderman I also wan to use the CRNN, would you please share the other CRNN version?

**Comment by freshcoderman** [comment]
@jiuhuazhao I modified the code wrote by novioleo in mxnet, here is the link https://github.com/novioleo/crnn.mxnet

**Comment by jiuhuazhao** [comment]
@freshcoderman Thanks a lot!

**Comment by GitHubGS** [comment]
https://github.com/facebook/thpp/issues/58 
you can take a look at this one, it works for me
