### ISSUE TITLE
Build error, can't find Torch configuration file

### ISSUE THREAD

**Issue by LinusU** [facebook/thpp#9]
I'm getting the following error when trying to compile thpp.

**command**
```sh
cmake ..
```

**stdout**
```text
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Folly: /usr/local/include  
-- Found Glog: /usr/include  
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/facebook/thpp/thpp/build/CMakeFiles/CMakeOutput.log".
```

**stderr**
```text
CMake Error at CMakeLists.txt:26 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by LinusU** [comment]
It turns out that my env wasn't properly setup. Running `source ~/torch/install/bin/activate-tource` before running `cmake` solved it.

**Comment by ruohoruotsi** [comment]
Thanks, this helped me get past this error as well, first time with Lua/Torch

**Comment by Sanjeev2487** [comment]
Hi @LinusU , for me it says no such file or directory. 
while conda list | grep torch gives the following -;

pytorch                   0.2.0           py27hc03bea1_4cu80  [cuda80]  soumith
torch                     0.2.0+4fc54af             <pip>
torchvision               0.1.9            py27hdb88a65_1    soumith

**Comment by msiraj83** [comment]
I found the same problem...

@LinusU  I run the command before cmake.. but did not work for me....
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 siraj@siraj-System-Product-Name:~/usr/src/thpp/thpp$ ls
build_fbthrift_folly.sh  StorageBase.h             TensorBase-inl.h
build.sh                 StorageBase-inl.h         Tensor.h
cmake                    Storage.cpp               Tensor-inl.h
CMakeLists.txt           Storage.h                 TensorPtr.h
cuda                     Storage-inl.h             TensorPtr-inl.h
detail                   StorageSerialization.cpp  TensorSerialization.cpp
if                       TensorBase.h              test
siraj@siraj-System-Product-Name:~/usr/src/thpp/thpp$ sudo ./build.sh 
If you don't have folly or thrift installed, try doing
  THPP_NOFB=1 ./build.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    119      0 --:--:--  0:00:01 --:--:--   119
100  618k  100  618k    0     0   181k      0  0:00:03  0:00:03 --:--:--  383k
curl: Saved to filename 'googletest-release-1.7.0.zip'
Archive:  googletest-release-1.7.0.zip
c99458533a9b4c743ed51537e25989ea55944908
   creating: googletest-release-1.7.0/
  inflating: googletest-release-1.7.0/CHANGES  
  inflating: googletest-release-1.7.0/CMakeLists.txt  
  inflating: googletest-release-1.7.0/CONTRIBUTORS  
  inflating: googletest-release-1.7.0/LICENSE  
  inflating: googletest-release-1.7.0/Makefile.am  
  inflating: googletest-release-1.7.0/README  
   creating: googletest-release-1.7.0/build-aux/
 extracting: googletest-release-1.7.0/build-aux/.keep  
   creating: googletest-release-1.7.0/cmake/
  inflating: googletest-release-1.7.0/cmake/internal_utils.cmake  
   creating: googletest-release-1.7.0/codegear/
  inflating: googletest-release-1.7.0/codegear/gtest.cbproj  
  inflating: googletest-release-1.7.0/codegear/gtest.groupproj  
  inflating: googletest-release-1.7.0/codegear/gtest_all.cc  
  inflating: googletest-release-1.7.0/codegear/gtest_link.cc  
  inflating: googletest-release-1.7.0/codegear/gtest_main.cbproj  
  inflating: googletest-release-1.7.0/codegear/gtest_unittest.cbproj  
  inflating: googletest-release-1.7.0/configure.ac  
   creating: googletest-release-1.7.0/include/
   creating: googletest-release-1.7.0/include/gtest/
  inflating: googletest-release-1.7.0/include/gtest/gtest-death-test.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest-message.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest-param-test.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest-param-test.h.pump  
  inflating: googletest-release-1.7.0/include/gtest/gtest-printers.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest-spi.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest-test-part.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest-typed-test.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest_pred_impl.h  
  inflating: googletest-release-1.7.0/include/gtest/gtest_prod.h  
   creating: googletest-release-1.7.0/include/gtest/internal/
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-death-test-internal.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-filepath.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-internal.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-linked_ptr.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-param-util-generated.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-param-util-generated.h.pump  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-param-util.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-port.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-string.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-tuple.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-tuple.h.pump  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-type-util.h  
  inflating: googletest-release-1.7.0/include/gtest/internal/gtest-type-util.h.pump  
   creating: googletest-release-1.7.0/m4/
  inflating: googletest-release-1.7.0/m4/acx_pthread.m4  
  inflating: googletest-release-1.7.0/m4/gtest.m4  
   creating: googletest-release-1.7.0/make/
  inflating: googletest-release-1.7.0/make/Makefile  
   creating: googletest-release-1.7.0/msvc/
  inflating: googletest-release-1.7.0/msvc/gtest-md.sln  
  inflating: googletest-release-1.7.0/msvc/gtest-md.vcproj  
  inflating: googletest-release-1.7.0/msvc/gtest.sln  
  inflating: googletest-release-1.7.0/msvc/gtest.vcproj  
  inflating: googletest-release-1.7.0/msvc/gtest_main-md.vcproj  
  inflating: googletest-release-1.7.0/msvc/gtest_main.vcproj  
  inflating: googletest-release-1.7.0/msvc/gtest_prod_test-md.vcproj  
  inflating: googletest-release-1.7.0/msvc/gtest_prod_test.vcproj  
  inflating: googletest-release-1.7.0/msvc/gtest_unittest-md.vcproj  
  inflating: googletest-release-1.7.0/msvc/gtest_unittest.vcproj  
   creating: googletest-release-1.7.0/samples/
  inflating: googletest-release-1.7.0/samples/prime_tables.h  
  inflating: googletest-release-1.7.0/samples/sample1.cc  
  inflating: googletest-release-1.7.0/samples/sample1.h  
  inflating: googletest-release-1.7.0/samples/sample10_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample1_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample2.cc  
  inflating: googletest-release-1.7.0/samples/sample2.h  
  inflating: googletest-release-1.7.0/samples/sample2_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample3-inl.h  
  inflating: googletest-release-1.7.0/samples/sample3_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample4.cc  
  inflating: googletest-release-1.7.0/samples/sample4.h  
  inflating: googletest-release-1.7.0/samples/sample4_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample5_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample6_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample7_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample8_unittest.cc  
  inflating: googletest-release-1.7.0/samples/sample9_unittest.cc  
   creating: googletest-release-1.7.0/scripts/
  inflating: googletest-release-1.7.0/scripts/fuse_gtest_files.py  
  inflating: googletest-release-1.7.0/scripts/gen_gtest_pred_impl.py  
  inflating: googletest-release-1.7.0/scripts/gtest-config.in  
  inflating: googletest-release-1.7.0/scripts/pump.py  
   creating: googletest-release-1.7.0/scripts/test/
  inflating: googletest-release-1.7.0/scripts/test/Makefile  
  inflating: googletest-release-1.7.0/scripts/upload.py  
  inflating: googletest-release-1.7.0/scripts/upload_gtest.py  
   creating: googletest-release-1.7.0/src/
  inflating: googletest-release-1.7.0/src/gtest-all.cc  
  inflating: googletest-release-1.7.0/src/gtest-death-test.cc  
  inflating: googletest-release-1.7.0/src/gtest-filepath.cc  
  inflating: googletest-release-1.7.0/src/gtest-internal-inl.h  
  inflating: googletest-release-1.7.0/src/gtest-port.cc  
  inflating: googletest-release-1.7.0/src/gtest-printers.cc  
  inflating: googletest-release-1.7.0/src/gtest-test-part.cc  
  inflating: googletest-release-1.7.0/src/gtest-typed-test.cc  
  inflating: googletest-release-1.7.0/src/gtest.cc  
  inflating: googletest-release-1.7.0/src/gtest_main.cc  
   creating: googletest-release-1.7.0/test/
  inflating: googletest-release-1.7.0/test/gtest-death-test_ex_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-death-test_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-filepath_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-linked_ptr_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-listener_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-message_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-options_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-param-test2_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-param-test_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-param-test_test.h  
  inflating: googletest-release-1.7.0/test/gtest-port_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-printers_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-test-part_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-tuple_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-typed-test2_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-typed-test_test.cc  
  inflating: googletest-release-1.7.0/test/gtest-typed-test_test.h  
  inflating: googletest-release-1.7.0/test/gtest-unittest-api_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_all_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_break_on_failure_unittest.py  
  inflating: googletest-release-1.7.0/test/gtest_break_on_failure_unittest_.cc  
  inflating: googletest-release-1.7.0/test/gtest_catch_exceptions_test.py  
  inflating: googletest-release-1.7.0/test/gtest_catch_exceptions_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_color_test.py  
  inflating: googletest-release-1.7.0/test/gtest_color_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_env_var_test.py  
  inflating: googletest-release-1.7.0/test/gtest_env_var_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_environment_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_filter_unittest.py  
  inflating: googletest-release-1.7.0/test/gtest_filter_unittest_.cc  
  inflating: googletest-release-1.7.0/test/gtest_help_test.py  
  inflating: googletest-release-1.7.0/test/gtest_help_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_list_tests_unittest.py  
  inflating: googletest-release-1.7.0/test/gtest_list_tests_unittest_.cc  
  inflating: googletest-release-1.7.0/test/gtest_main_unittest.cc  
  inflating: googletest-release-1.7.0/test/gtest_no_test_unittest.cc  
  inflating: googletest-release-1.7.0/test/gtest_output_test.py  
  inflating: googletest-release-1.7.0/test/gtest_output_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_output_test_golden_lin.txt  
  inflating: googletest-release-1.7.0/test/gtest_pred_impl_unittest.cc  
  inflating: googletest-release-1.7.0/test/gtest_premature_exit_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_prod_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_repeat_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_shuffle_test.py  
  inflating: googletest-release-1.7.0/test/gtest_shuffle_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_sole_header_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_stress_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_test_utils.py  
  inflating: googletest-release-1.7.0/test/gtest_throw_on_failure_ex_test.cc  
  inflating: googletest-release-1.7.0/test/gtest_throw_on_failure_test.py  
  inflating: googletest-release-1.7.0/test/gtest_throw_on_failure_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_uninitialized_test.py  
  inflating: googletest-release-1.7.0/test/gtest_uninitialized_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_unittest.cc  
  inflating: googletest-release-1.7.0/test/gtest_xml_outfile1_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_xml_outfile2_test_.cc  
  inflating: googletest-release-1.7.0/test/gtest_xml_outfiles_test.py  
  inflating: googletest-release-1.7.0/test/gtest_xml_output_unittest.py  
  inflating: googletest-release-1.7.0/test/gtest_xml_output_unittest_.cc  
  inflating: googletest-release-1.7.0/test/gtest_xml_test_utils.py  
  inflating: googletest-release-1.7.0/test/production.cc  
  inflating: googletest-release-1.7.0/test/production.h  
   creating: googletest-release-1.7.0/xcode/
   creating: googletest-release-1.7.0/xcode/Config/
  inflating: googletest-release-1.7.0/xcode/Config/DebugProject.xcconfig  
  inflating: googletest-release-1.7.0/xcode/Config/FrameworkTarget.xcconfig  
  inflating: googletest-release-1.7.0/xcode/Config/General.xcconfig  
  inflating: googletest-release-1.7.0/xcode/Config/ReleaseProject.xcconfig  
  inflating: googletest-release-1.7.0/xcode/Config/StaticLibraryTarget.xcconfig  
  inflating: googletest-release-1.7.0/xcode/Config/TestTarget.xcconfig  
   creating: googletest-release-1.7.0/xcode/Resources/
  inflating: googletest-release-1.7.0/xcode/Resources/Info.plist  
   creating: googletest-release-1.7.0/xcode/Samples/
   creating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/Info.plist  
   creating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/WidgetFramework.xcodeproj/
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/WidgetFramework.xcodeproj/project.pbxproj  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/runtests.sh  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/widget.cc  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/widget.h  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/widget_test.cc  
   creating: googletest-release-1.7.0/xcode/Scripts/
  inflating: googletest-release-1.7.0/xcode/Scripts/runtests.sh  
  inflating: googletest-release-1.7.0/xcode/Scripts/versiongenerate.py  
   creating: googletest-release-1.7.0/xcode/gtest.xcodeproj/
  inflating: googletest-release-1.7.0/xcode/gtest.xcodeproj/project.pbxproj  
dirname: missing operand
Try 'dirname --help' for more information.
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:26 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/siraj/usr/src/thpp/thpp/build/CMakeFiles/CMakeOutput.log".
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Although i install Torch and add the Include and lib path to $PATH and $LD_LIBRARY_PATH

Can anybody help me

Thanks

**Comment by ginobilinie** [comment]
@msiraj83 Have you solved it? I have the same issue. I have tired the "source ..." suggestion, it doesn't work.

**Comment by msiraj83** [comment]
@ginobilinie ..You will try the with following configuration..

- Ubuntu 14.04

- Cuda version 7 or 8
Moreover, i found this scripts... it work for me ...
`#!/bin/bash -e
#
#  Copyright (c) 2014, Facebook, Inc.
#  All rights reserved.
#
#  This source code is licensed under the BSD-style license found in the
#  LICENSE file in the root directory of this source tree. An additional grant
#  of patent rights can be found in the PATENTS file in the same directory.
#

echo
echo This script will install fblualib and all its dependencies.
echo It has been tested on Ubuntu 13.10 and Ubuntu 14.04, Linux x86_64.
echo

set -e
set -x


if [[ $(arch) != 'x86_64' ]]; then
    echo "x86_64 required" >&2
    exit 1
fi

issue=$(cat /etc/issue)
extra_packages=
current=0
if [[ $issue =~ ^Ubuntu\ 13\.10 ]]; then
    :
elif [[ $issue =~ ^Ubuntu\ 14 ]]; then
    extra_packages=libiberty-dev
elif [[ $issue =~ ^Ubuntu\ 15\.04 ]]; then
    extra_packages=libiberty-dev
elif [[ $issue =~ ^Ubuntu\ 16\.04 ]]; then
    extra_packages=libiberty-dev
    current=1
else
    echo "Ubuntu 13.10, 14.*, 15.04 or 16.04 required" >&2
    exit 1
fi

#dir=$(mktemp --tmpdir -d fblualib-build.XXXXXX)
dir=$HOME/torch3/
echo Working in $dir
echo
cd $dir

echo Installing required packages
echo
sudo apt-get install -y \
    git \
    curl \
    wget \
    g++ \
    automake \
    autoconf \
    autoconf-archive \
    libtool \
    libboost-all-dev \
    libevent-dev \
    libdouble-conversion-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    liblz4-dev \
    liblzma-dev \
    libsnappy-dev \
    make \
    zlib1g-dev \
    binutils-dev \
    libjemalloc-dev \
    $extra_packages \
    flex \
    bison \
    libkrb5-dev \
    libsasl2-dev \
    libnuma-dev \
    pkg-config \
    libssl-dev \
    libedit-dev \
    libmatio-dev \
    libpython-dev \
    libpython3-dev \
    python-numpy

echo
echo Cloning repositories
echo
if [ $current -eq 1 ]; then
    git clone --depth 1 https://github.com/facebook/folly
    git clone --depth 1 https://github.com/facebook/fbthrift
    git clone https://github.com/facebook/thpp
    git clone https://github.com/facebook/fblualib
    git clone https://github.com/facebook/wangle
else
    git clone -b v0.35.0  --depth 1 https://github.com/facebook/folly
    git clone -b v0.24.0  --depth 1 https://github.com/facebook/fbthrift
    git clone -b v1.0 https://github.com/facebook/thpp
    git clone -b v1.0 https://github.com/facebook/fblualib
fi

echo
echo Building folly
echo

cd $dir/folly/folly
autoreconf -ivf
./configure
make
sudo make install
sudo ldconfig # reload the lib paths after freshly installed folly. fbthrift needs it.

if [ $current -eq 1 ]; then
    echo
    echo Wangle
    echo

    cd $dir/wangle/wangle
    cmake .
    make
    sudo make install
fi

echo
echo Building fbthrift
echo

cd $dir/fbthrift/thrift
autoreconf -ivf
./configure
if [ $current -eq 1 ]; then
    pushd lib/cpp2/fatal/internal
    ln -s folly_dynamic-inl-pre.h folly_dynamic-inl.h
    popd
fi
make
sudo make install

echo
echo 'Installing TH++'
echo

cd $dir/thpp/thpp
./build.sh

echo
echo 'Installing FBLuaLib'
echo

cd $dir/fblualib/fblualib
./build.sh

echo
echo 'All done!'
echo`
